### ISSUE TITLE
outline never starts from the top

### ISSUE THREAD

**Issue by marciocoragem** [GridSpace/grid-apps#158]
The outline never starts from the top on some shapes.
![Screenshot_20210425_140746](https://user-images.githubusercontent.com/23552991/115994645-c8c37c80-a5cf-11eb-9ae6-d8913de648e7.png)

I have tried multiple combinations and nothing works.

**Comment by stewartoallen** [comment]
Outline never starts at the top of a part since it is meant to remove material. You can force tops and faces to be cleared with a roughing operation or you can use a trace/clear operation to clean one face of a part.

**Comment by marciocoragem** [comment]
I understand that but as you can see in the imagem it starts a lot lower than supposed to, and why in the holes it starts from the top?
In this file i'm using a rough with 1mm depth of pass and them use a outline with 0,2 to clean up the surface (kind of like a finishing pass with a ballnose).

This works nice and gives a good finishing surface everywhere except in the first 2 or 3mm.

**Comment by marciocoragem** [comment]
Another thing is that i used the contour feature before with success, but now i have some problems. I have select the options use only curves and inside only, but it generates toolpaths in the top of the stock, like you can see in the images.
![image](https://user-images.githubusercontent.com/23552991/115999802-20201780-a5e5-11eb-9b62-180cf313b34b.png)

**Comment by stewartoallen** [comment]
Please right-click and export your workspace. Then either drop a zipped up `.km` file here or email it to sa@grid.space -- thank you

**Comment by marciocoragem** [comment]
Thanks for taking a look.

[workspace.km.zip](https://github.com/GridSpace/grid-apps/files/6375233/workspace.km.zip)

**Comment by stewartoallen** [comment]
I have a fix for the curves only contouring that I will push out later today.

Before

<img width="1600" alt="Screen Shot 2021-04-26 at 9 10 07 AM" src="https://user-images.githubusercontent.com/554275/116088291-bbf66580-a66f-11eb-847d-96e1d09c90f0.png">

After

<img width="1600" alt="Screen Shot 2021-04-26 at 9 10 29 AM" src="https://user-images.githubusercontent.com/554275/116088348-c7e22780-a66f-11eb-8dd7-249b270b868f.png">

**Comment by stewartoallen** [comment]
Your other problem is caused by the geometry of the part. The interior pocket is joined at the top by two exterior pockets that extend to the outside of the part which causes them to be considered "outside". So the outline inside-only option you have checked causes those cuts to be removed.

<img width="514" alt="Screen Shot 2021-04-26 at 9 12 23 AM" src="https://user-images.githubusercontent.com/554275/116088442-de887e80-a66f-11eb-8fc4-e2354eff48cf.png">

With the way the outline operation works at present, the workaround is this:

disable `inside only`
set stock offset to 0, 0, 0
only mill one part at a time so the stock clipping will work as expected

<img width="1600" alt="Screen Shot 2021-04-26 at 9 13 10 AM" src="https://user-images.githubusercontent.com/554275/116088833-3aeb9e00-a670-11eb-96bc-654f96c23dd5.png">

**Comment by marciocoragem** [comment]
Thanks,
I will try those settings.

This is by far my favorite free CAM software, i really like how it works with stl files.

**Comment by stewartoallen** [comment]
Thank you!
