### ISSUE TITLE
Unexpected contour behavior 

### ISSUE THREAD

**Issue by geobruce** [GridSpace/grid-apps#165]
All vertical walls have straight edges except for the inner "dome". 
![image](https://user-images.githubusercontent.com/4906120/118127053-7371d280-b3f9-11eb-9b41-3c4592c33e51.png)

![image](https://user-images.githubusercontent.com/4906120/118127016-65bc4d00-b3f9-11eb-86d6-0a71a3dcde5a.png)

But I see a lot of tool paths around the straight edges.

[straight edge countour weird behavior.zip](https://github.com/GridSpace/grid-apps/files/6472479/straight.edge.countour.weird.behavior.zip)

**Comment by stewartoallen** [comment]
because you have a ball mill selected, it generates curved paths over edges

<img width="759" alt="Screen Shot 2021-05-13 at 9 24 49 AM" src="https://user-images.githubusercontent.com/554275/118131958-27109d80-b3cd-11eb-9cd2-f2a4ce1e5e83.png">

same settings with an standard endmill

<img width="770" alt="Screen Shot 2021-05-13 at 9 25 03 AM" src="https://user-images.githubusercontent.com/554275/118132022-3bed3100-b3cd-11eb-9b85-b2b3a9d0e82f.png">

**Comment by stewartoallen** [comment]
the algorithm as it stands looks for linear horizontal cutting paths and removes them. it will have to be re-imagined to exhibit the behavior you're expecting. but now that I see it, I can think of ways to achieve it. so I will add it to the 3.0 list.
