### ISSUE TITLE
OnShape integration fails silently with 3rd party cookies disabled

### ISSUE THREAD

**Issue by xxv** [GridSpace/grid-apps#33]
When 3rd party cookies are disabled, the OnShape Kiri:Moto app fails silently.

In Firefox 57.0 on Debian/testing (Buster), if you set:
`network.cookie.cookieBehavior=1`
the main Kiri:Moto UI doesn't display:

![0x1617be1a](https://user-images.githubusercontent.com/124381/38816884-193a03dc-4165-11e8-9a8a-dc89a4e54869.png)

**Comment by stewartoallen** [comment]
known issue.  will add a dialog.  "3rd party cookies" is a misnomer and as it covers local storage and indexeddb as well.  kiri needs those to store meshes and do other computations.  since onshape iframes apps, this causes the "3rd party" issue.  if you visit grid.space/kiri directly in your browser *then* go to onshape, it should be promoted to a "1st party" and avoid the issue.

**Comment by stewartoallen** [comment]
This no longer fails silently. It gives you a visual warning. However, it still prevents Kiri from operating.
