### ISSUE TITLE
Problem when running kiri locally

### ISSUE THREAD

**Issue by arifbalik** [GridSpace/grid-apps#82]
I'm new to nodejs so if this is an easy fix or not worth opening an issue for, please excuse me.

I downloaded the source and run
```bash
sudo apt-get install npm
npm install utf8-validate
npm install bufferutil
npm i
npm start
```

After that I'm getting almost an empty page, when I look at the console output I get following error messages;
![error](https://user-images.githubusercontent.com/7956654/82305816-d8514300-99c6-11ea-8735-eefbe95cc900.PNG)

**Comment by stewartoallen** [comment]
If you are attempting this on Windows, then it has difficulty with symbolic file links. You will need to re-clone the git directory using a command shell that is running with administrator privileges. Otherwise you will see that the files contain the names of the linked file instead of the linked file contents.
